apiVersion: pollination.cloud/v1
kind: SecretsFromGCP
metadata:
  name: secret-name
  namespace: default
source:
  projectId: pollination-staging-1d6a8
  name: kustomization-plugin-example-secret
  version: latest
keys:
  - username
  - password
---
apiVersion: pollination.cloud/v1
kind: SecretsFromGCP
metadata:
  name: host-name
  namespace: default
source:
  projectId: pollination-staging-1d6a8
  name: kustomization-plugin-example-secret
  version: latest
keys:
  - host