steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '--tag=gcr.io/$PROJECT_ID/kustomize:$COMMIT_SHA'
      - '--tag=gcr.io/$PROJECT_ID/kustomize:latest'
      - .
    id: Build
images:
  - gcr.io/$PROJECT_ID/kustomize:$COMMIT_SHA
  - gcr.io/$PROJECT_ID/kustomize:latest